"""add office auxiliary stock tables

Revision ID: 656bdb3e32f8
Revises: f5a18fea31ef
Create Date: 2026-02-05 13:45:40.093366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '656bdb3e32f8'
down_revision: Union[str, Sequence[str], None] = 'f5a18fea31ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_sales')
    op.drop_table('delivery_payroll')
    op.drop_table('delivery_transfers')
    op.drop_table('users')
    op.drop_table('cash_handovers')
    op.drop_table('app_users')
    op.drop_table('office_expenses')
    op.drop_table('delivery_cylinder_detail')
    op.drop_table('office_cash_day')
    op.drop_table('delivery_trips')
    op.drop_index(op.f('ix_bda_sales_id'), table_name='bda_sales')
    op.drop_table('bda_sales')
    op.drop_table('delivery_day_summary')
    op.drop_table('delivery_men')
    op.drop_table('stock_day_end')
    op.drop_table('cash_denominations')
    op.drop_table('staff_advances')
    op.drop_table('stock_movements')
    op.drop_table('bdas')
    op.drop_table('stock_opening')
    op.drop_table('stock_locations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location_type', sa.VARCHAR(), nullable=True),
    sa.Column('ref_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_opening',
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('location_id', sa.INTEGER(), nullable=False),
    sa.Column('filled_qty', sa.INTEGER(), nullable=True),
    sa.Column('empty_qty', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['stock_locations.id'], ),
    sa.PrimaryKeyConstraint('date', 'location_id')
    )
    op.create_table('bdas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('village', sa.VARCHAR(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('from_location', sa.INTEGER(), nullable=True),
    sa.Column('to_location', sa.INTEGER(), nullable=True),
    sa.Column('filled_qty', sa.INTEGER(), nullable=True),
    sa.Column('empty_qty', sa.INTEGER(), nullable=True),
    sa.Column('reason', sa.VARCHAR(), nullable=True),
    sa.Column('ref_type', sa.VARCHAR(), nullable=True),
    sa.Column('ref_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_advances',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('staff_type', sa.VARCHAR(), nullable=True),
    sa.Column('staff_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('recovered', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_denominations',
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('n2000', sa.INTEGER(), nullable=True),
    sa.Column('n500', sa.INTEGER(), nullable=True),
    sa.Column('n200', sa.INTEGER(), nullable=True),
    sa.Column('n100', sa.INTEGER(), nullable=True),
    sa.Column('n50', sa.INTEGER(), nullable=True),
    sa.Column('n20', sa.INTEGER(), nullable=True),
    sa.Column('n10', sa.INTEGER(), nullable=True),
    sa.Column('coins', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('stock_day_end',
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('location_id', sa.INTEGER(), nullable=False),
    sa.Column('filled_qty', sa.INTEGER(), nullable=True),
    sa.Column('empty_qty', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['stock_locations.id'], ),
    sa.PrimaryKeyConstraint('date', 'location_id')
    )
    op.create_table('delivery_men',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('mobile', sa.VARCHAR(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deactivated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_day_summary',
    sa.Column('delivery_man_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('total_cylinders', sa.INTEGER(), nullable=False),
    sa.Column('day_type', sa.VARCHAR(), nullable=False),
    sa.Column('helper_used', sa.BOOLEAN(), nullable=True),
    sa.Column('confirmed_by', sa.VARCHAR(), nullable=True),
    sa.Column('confirmed_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('delivery_man_id', 'date')
    )
    op.create_table('bda_sales',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bda_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('filled_out', sa.INTEGER(), nullable=True),
    sa.Column('empty_in', sa.INTEGER(), nullable=True),
    sa.Column('cash_collected', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['bda_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bda_sales_id'), 'bda_sales', ['id'], unique=False)
    op.create_table('delivery_trips',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('delivery_man_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('trip_no', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_man_id'], ['delivery_men.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('office_cash_day',
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('opening_cash', sa.INTEGER(), nullable=True),
    sa.Column('cash_in', sa.INTEGER(), nullable=True),
    sa.Column('cash_out', sa.INTEGER(), nullable=True),
    sa.Column('closing_expected', sa.INTEGER(), nullable=True),
    sa.Column('closing_counted', sa.INTEGER(), nullable=True),
    sa.Column('difference', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('delivery_cylinder_detail',
    sa.Column('delivery_man_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('area_type', sa.VARCHAR(), nullable=False),
    sa.Column('cylinders', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('delivery_man_id', 'date', 'area_type')
    )
    op.create_table('office_expenses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('head', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('remark', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('login_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_id')
    )
    op.create_table('cash_handovers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_type', sa.VARCHAR(), nullable=True),
    sa.Column('source_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('payment_mode', sa.VARCHAR(), nullable=True),
    sa.Column('receiver_type', sa.VARCHAR(), nullable=True),
    sa.Column('receiver_name', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('delivery_transfers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trip_id', sa.INTEGER(), nullable=False),
    sa.Column('to_location_id', sa.INTEGER(), nullable=False),
    sa.Column('filled_qty', sa.INTEGER(), nullable=True),
    sa.Column('empty_qty', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['to_location_id'], ['stock_locations.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['delivery_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_payroll',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('delivery_man_id', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.VARCHAR(), nullable=False),
    sa.Column('base_wage', sa.INTEGER(), nullable=False),
    sa.Column('helper_days', sa.INTEGER(), nullable=False),
    sa.Column('helper_amount', sa.INTEGER(), nullable=False),
    sa.Column('gross', sa.INTEGER(), nullable=False),
    sa.Column('advance_recovered', sa.INTEGER(), nullable=False),
    sa.Column('net_paid', sa.INTEGER(), nullable=False),
    sa.Column('payment_mode', sa.VARCHAR(), nullable=False),
    sa.Column('payment_date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_sales',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trip_id', sa.INTEGER(), nullable=True),
    sa.Column('payment_mode', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['delivery_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
