"""initial_erp_schema

Revision ID: f5a18fea31ef
Revises: 
Create Date: 2026-02-04 13:44:34.240138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a18fea31ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('godown_physical_log')
    op.drop_table('locations')
    op.drop_table('roles_permissions')
    op.drop_table('cash_ledger')
    op.drop_table('users')
    op.drop_table('bda_ledger')
    op.drop_table('products')
    op.drop_table('staff_advances')
    op.drop_table('office_expenses')
    op.drop_table('stock_ledger')
    op.drop_table('trip_header')
    op.drop_table('vehicles')
    op.drop_table('cash_denomination')
    op.drop_table('erp_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_day',
    sa.Column('date', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('opened_at', sa.DATETIME(), nullable=True),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.Column('closed_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('cash_denomination',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('erp_date', sa.VARCHAR(), nullable=False),
    sa.Column('location', sa.INTEGER(), nullable=False),
    sa.Column('denomination_json', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reg_name', sa.VARCHAR(), nullable=False),
    sa.Column('capacity', sa.INTEGER(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_header',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('erp_date', sa.VARCHAR(), nullable=False),
    sa.Column('delivery_man', sa.INTEGER(), nullable=False),
    sa.Column('vehicle', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('opened_at', sa.DATETIME(), nullable=True),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_ledger',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('erp_date', sa.VARCHAR(), nullable=False),
    sa.Column('product_code', sa.VARCHAR(), nullable=False),
    sa.Column('from_location', sa.INTEGER(), nullable=True),
    sa.Column('to_location', sa.INTEGER(), nullable=True),
    sa.Column('qty', sa.INTEGER(), nullable=False),
    sa.Column('reason', sa.VARCHAR(), nullable=False),
    sa.Column('ref_type', sa.VARCHAR(), nullable=False),
    sa.Column('ref_id', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('office_expenses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('erp_date', sa.VARCHAR(), nullable=False),
    sa.Column('head', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_advances',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('erp_date', sa.VARCHAR(), nullable=False),
    sa.Column('staff_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('bda_ledger',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('erp_date', sa.VARCHAR(), nullable=False),
    sa.Column('bda_id', sa.INTEGER(), nullable=False),
    sa.Column('product_code', sa.VARCHAR(), nullable=False),
    sa.Column('qty', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('mobile', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('pin_hash', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile')
    )
    op.create_table('cash_ledger',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('erp_date', sa.VARCHAR(), nullable=False),
    sa.Column('location', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('mode', sa.VARCHAR(), nullable=False),
    sa.Column('denomination_json', sa.VARCHAR(), nullable=True),
    sa.Column('reason', sa.VARCHAR(), nullable=False),
    sa.Column('ref_type', sa.VARCHAR(), nullable=True),
    sa.Column('ref_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('permission_code', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('godown_physical_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('erp_date', sa.VARCHAR(), nullable=False),
    sa.Column('product_code', sa.VARCHAR(), nullable=False),
    sa.Column('physical_qty', sa.INTEGER(), nullable=False),
    sa.Column('recorded_by', sa.INTEGER(), nullable=False),
    sa.Column('recorded_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
